name:
  new_cop3e

channels:
  - defaults
  - bioconda

dependencies:
  - jupyterlab=4.0.11
  - biopython=1.78
  - pyfaidx=0.8.1.1
  - matplotlib=3.8.4
  - tqdm=4.66.4
  - ipywidgets=8.1.2
  - scikit-learn=1.4.2
  - pandas=2.2.2
  - seaborn=0.13.2
  - pip=23.3.1
  - pip:
    - shap==0.46.0